strategy: fromscratch
# Reference: https://github.com/facebookresearch/SlowFast/blob/main/configs/Kinetics/SLOWFAST_8x8_R50.yaml
lr: 0.1
momentum: 0.9
wd: 1e-4
warmup_epochs: 35
warmup_start_lr: 0.01
max_epochs: 200