_target_: models.VideoClassificationModule
optim:
  optimizer:
    _target_: torch.optim.SGD
    params: ???
    lr: 0.1
    momentum: 0.9
    weight_decay: 1e-4
  scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    optimizer: ???
    T_max: ${trainer.max_epochs}