dir_moma: /home/alanzluo/data/moma
dir_wandb: /home/alanzluo/log
dir_weights: /home/alanzluo/data/weights

levels: [act, sact]
backbone: mvit
strategy: finetune

num_classes:
  act: 20
  sact: 91

gpus: [0, 1, 2, 3, 4, 5, 6, 7]
num_workers: 3

batch_size: 64
fps: 30
lr: 0.03
momentum: 0.9
wd: 1e-4
warmup_steps: 500
num_epochs: 50

# sampling
num_crops: 3
num_clips: 10
T:
  mvit: 16
  slowfast: 8
  s3d: 30
tau:
  mvit: 4
  slowfast: 8
  s3d: 1
alpha: 4