defaults:
  - data: default
  - model: default
  - trainer: default
  - data/backbone@data: mvit
  - data/level@data: sact
  - model/backbone@model: ${data/backbone@data}
  - model/strategy@model: finetune
  - _self_

root: /home/alanzluo