dir_moma: /home/alanzluo/data/moma
dir_wandb: /home/alanzluo/log
dir_weights: /home/alanzluo/data/weights

levels: [act, sact]
net: mvit
optimizer: adamw
mode: finetune
few_shot: False
weight: pretrain

gpus: [0, 1, 2, 3, 4, 5, 6, 7]
num_workers: 3

num_epochs: 30
warmup_steps: 100
batch_size: 128
fps: 30
lr:
  sgd: 0.24
  adamw: 0.0008
momentum: 0.9
wd:
  sgd: 1e-4
  adamw: 0.05

num_crops: 3
num_clips: 10
T: 16
tau: 4
