dir_moma: /home/alanzluo/data/moma
dir_wandb: /home/alanzluo/log
dir_weights: /home/alanzluo/data/weights

levels: [act, sact]
net: s3d
optimizer: sgd
mode: finetune
few_shot: True

gpus: [0, 1, 2, 3, 4, 5, 6, 7]
num_workers: 3

batch_size: 64
fps: 30
lr: 0.03
momentum: 0.9
wd: 1e-4
warmup_steps: 500
num_epochs: 30

# sampling
num_crops: 3
num_clips: 10
T: 30
tau: 1